# Generated by Django 3.2.19 on 2024-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Table', '0002_auto_20240904_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='profiles/default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
